/usr/lib/python3.4/site-packages/deap/tools/_hypervolume/pyhv.py:33: ImportWarning: Falling back to the python version of hypervolume module. Expect this to be very slow.
  "module. Expect this to be very slow.", ImportWarning)
Process ForkPoolWorker-10:
Traceback (most recent call last):
  File "/usr/lib64/python3.4/multiprocessing/process.py", line 254, in _bootstrap
    self.run()
  File "/usr/lib64/python3.4/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib64/python3.4/multiprocessing/pool.py", line 108, in worker
    task = get()
  File "/usr/lib64/python3.4/multiprocessing/queues.py", line 360, in get
    res = self._reader.recv_bytes()
  File "/usr/lib64/python3.4/multiprocessing/connection.py", line 216, in recv_bytes
    buf = self._recv_bytes(maxlength)
  File "/usr/lib64/python3.4/multiprocessing/connection.py", line 420, in _recv_bytes
    return self._recv(size)
  File "/usr/lib64/python3.4/multiprocessing/connection.py", line 392, in _recv
    buf.write(chunk)
MemoryError
multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/usr/lib64/python3.4/multiprocessing/pool.py", line 119, in worker
    result = (True, func(*args, **kwds))
  File "/usr/lib64/python3.4/multiprocessing/pool.py", line 47, in starmapstar
    return list(itertools.starmap(args[0], args[1]))
  File "./lib/Methods.py", line 89, in getModelApproach
    params = _individual_to_params(individual, parametros)
  File "./lib/Methods.py", line 138, in _individual_to_params
    return dict((name, values[gene]) for gene, (name, values) in zip(individual, name_values))
  File "./lib/Methods.py", line 138, in <genexpr>
    return dict((name, values[gene]) for gene, (name, values) in zip(individual, name_values))
IndexError: list index out of range
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "main.py", line 58, in <module>
    ev.fit(scoring='mse', n_jobs=cpu_count(), kargs=searchParams)
  File "/home/Manuel.Castillo/pruebasOHC/lib/ProcessManager.py", line 44, in fit
    edcv.run()
  File "./lib/edasSearch.py", line 105, in run
    self.evaluate()  # Multi process
  File "./lib/edasSearch.py", line 84, in evaluate
    self.sample[:, -1] = _pool.starmap(self.objective_function, _iterable)
  File "/usr/lib64/python3.4/multiprocessing/pool.py", line 268, in starmap
    return self._map_async(func, iterable, starmapstar, chunksize).get()
  File "/usr/lib64/python3.4/multiprocessing/pool.py", line 608, in get
    raise self._value
IndexError: list index out of range
